# Generated by Django 3.2 on 2022-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='old_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='maincatalogmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subcatalogmodel',
            table=None,
        ),
    ]
